language: ruby
rvm:
  - 2.4.5

# Make sure we can execute our scripts
before_script:
  - chmod +x ./_tools/build

script: ./_tools/build

# master is the publish branch to pages, so we don't want to build that one.
branches:
  except:
    - master

env:
  global:
    - JEKYLL_ENV=production
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
      - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build
cache: bundler # caching bundler gem packages will speed up build

notifications:
  email: true

before_deploy:
  - sed -i '/_site/d' .gitignore

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # This is stored in the Travis Settings
  keep-history: true
  on:
    branch: sources
  target-branch: master
  local-dir: _site

