# Site settings
title: Todd H. Gardner
description: > # this means to ignore newlines until "baseurl:"
  Hey! I'm Todd. I develop businesses and build software. I'm the President and Cofounder
  of TrackJS and the Producer of PubConf. I also consult, train, and speak at all kinds of
  organizations.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://toddhgardner.com" # the base hostname & protocol for your site
image: "/assets/img/toddhgardner-og.jpg"

permalink: /:categories/:title/

markdown: kramdown
highlighter: rouge
encoding: utf-8

sass:
  sass_dir: "assets/css"

plugins:
  - jekyll-redirect-from

exclude:
  - "Gemfile*"
  - "README.md"
  - "LICENSE"

include:
  - ".well-known"
